### ISSUE TITLE
Thai Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/th.reactjs.org#1]
## Maintainer List

* @kiroskirin
* @iphayao
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@iphayao) #2
* [x] Tutorial (@kiroskirin ) #3 

### Basics

* [x] Hello World (@kiroskirin) #4 
* [x] Introducing JSX (@kiroskirin) #5 
* [x] Rendering Elements (@kiroskirin) #6 
* [x] Components and Props (@gie3d) #10 
* [x] State and Lifecycle (@javadevil) #11 
* [x] Handling Events (@gie3d) #13
* [x] Conditional Rendering (@javadevil) #12 
* [x] Lists and Keys (@javadevil) #16
* [x] Forms (@svnnynior) #28 
* [ ] Lifting State Up
* [ ] Composition vs Inheritance
* [ ] Thinking in React

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@iphayao) #27 
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started
* [ ] Add React to a Website
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited about these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@kiroskirin @iphayao please use this issue to keep track of your translation progress, and let me know if you have any questions!

**Comment by tesseralis** [comment]
@kiroskirin @iphayao how is it going? do you need any additional help to get started on translations?

**Comment by kiroskirin** [comment]
@tesseralis Unfortunate that my schedule is quite full in the next few weeks. When I've some free time I would jump into it right away :)

**Comment by iphayao** [comment]
@tesseralis How to edit this page?

**Comment by tesseralis** [comment]
@iphayao you should have received an invite to join the reactjs organization. I'll resend it, and once you join you should be able to edit this page.

**Comment by gie3d** [comment]
Hello, I'd like to translate this page in to Thai: Components and Props

**Comment by kiroskirin** [comment]
@gie3d จัดเลยครับ 

แต่ผมไม่แน่ใจว่าอาจจะต้องทำตาม Guide นี้ก่อนหรือเปล่านะครับ

https://github.com/reactjs/reactjs.org-translation#translating-reactjsorg

**Comment by gie3d** [comment]
@kiroskirin ขอบคุณครับ 
เท่าที่ลองดูใน link น่าจะเป็นการขอเป็น maintainer ของ project ซึ่งผมน่าจะยังไม่ถึงขั้นนั้น (ยังไม่เคยมีแปลจริงๆจัง) ถ้ายังไงจะลองแปลหน้าตามใน list เท่าที่เวลาจะพอมีก่อนครับ ถ้าพอใช้ได้และดูท่าจะมีเวลาค่อยขอ add เข้าเป็น maintainer ครับ

**Comment by javadevil** [comment]
ถ้าเราจะช่วยแปลคือ fork repo นี้แล้วแก้ content แล้ว pull request เข้ามาใช่ไหมครับ?

**Comment by gie3d** [comment]
มีเพิ่มเติมอีกนิดครับคือ
- ให้เลือก page ที่จะแปลจาก list ข้างบน (ให้เลือกหน้าที่ยังไม่มีคนแปล)
- เลือกหน้าที่จะแปลได้แล้วให้เขียน comment ไว้ เพื่อให้ maintainer มา edit thread นี้ว่าเรากำลังจะแปลหน้านั้น

**Comment by javadevil** [comment]
งั้น State and life cycle

**Comment by iphayao** [comment]
Fork ไปแปลกันได้เลยครับ หรือถ้าใครอยากเป็น maintainer ก็ได้นะครับ ^_^

**Comment by javadevil** [comment]
ผมอยากถามว่าพวกศัพท์เฉพาะ เราควรแปลกันอย่างไรครับ เช่น React, Props, State ควรมี issues สำหรับคำเหล่านี้ไหม?

**Comment by gie3d** [comment]
ผม vote ทับศัพท์คำว่า props = พรอพส์, state = สเตท ไปเลยครับ เพราะว่าคำเหล่านี้เป็น syntax ที่จะต้องไปเห็นใน code ด้วย ถ้าแปลเป็นภาษาไทยแล้วไปดู code อาจจะต้องใช้เวลาทำความเข้าใจมากขึ้น

**Comment by gie3d** [comment]
I'd like to translate: Handling Events

**Comment by javadevil** [comment]
translate: Conditional Rendering

**Comment by javadevil** [comment]
translate:  Lists and Keys

**Comment by durunvo** [comment]
> ผม vote ทับศัพท์คำว่า props = พรอพส์, state = สเตท ไปเลยครับ เพราะว่าคำเหล่านี้เป็น syntax ที่จะต้องไปเห็นใน code ด้วย ถ้าแปลเป็นภาษาไทยแล้วไปดู code อาจจะต้องใช้เวลาทำความเข้าใจมากขึ้น

เวลาเราเอาไป google เราจะได้รู้ว่าคนทั่วโลกเขาใช้ keyword ว่าอะไร แต่ถ้าเราใช้คำไทยเขียนเราจะค้น google ไม่เจอครับ

**Comment by kiroskirin** [comment]
ถ้าเอาแบบตามหนังสือเรียนที่เป็นภาษาไทย แล้วแปรคำภาษาต่างประเทศ ส่วนใหญ่ที่เห็นมักนิยมใช้แบบนี้

สเตท (State), พรอพส์ (Props)

ถ้าแปลไทยได้ก็แปล แล้วมีวงเล็บเป็นคำภาษาอังกฤษไว้ด้วย ผมว่าแบบนี้น่าจะโอเคนะ

**Comment by svnnynior** [comment]
Hello, I would like to translate: **Forms** krub.

**Comment by svnnynior** [comment]
Hi ครับ @iphayao, ผมพึ่งเห็นว่าพี่เริ่มแปลหน้า Forms เมื่อประมาณ 4 วันที่แล้วอะครับ ซึ่งหน้านี้ตอนนี้ผมแปลเสร็จแล้วอยู่ที่ #28 ครับ เลยอยากแจ้งไว้เผื่อว่าจะได้ไม่ต้องแปลซ้ำกัน

**Comment by svnnynior** [comment]
I would like to translate **Lifting State Up** next krub.

**Comment by sirkeng** [comment]
Hello, I would like to translate **Composition vs Inheritance** 

ปล.ผมมือใหม่ ยังไม่เข้าร่วม contribute ที่ไหน แนะนำด้วยนะครับ

**Comment by KorawitRupanya** [comment]
Pls update the README above to make it more clarify for others which would like to contribute to this project.

**Comment by naruthk** [comment]
I'm new to this community krub, but I would like to help with the translations from now on krub.

I saw the content on the homepage still had some conflict issues. Please see this PR krub: #67

**Comment by nathansom** [comment]
Is this project still ongoing or being deprecated? If it's still ongoing, can I please apply to become a maintainer? 

Thank you krub.

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
